all:
	gcc client_async.c -I /opt/Linaro/open62541.git/build/ -L /opt/Linaro/open62541.git/build/bin -l open62541 -o client_async
	gcc server_ctt.c -I /opt/Linaro/open62541.git/build/ -L /opt/Linaro/open62541.git/build/bin -l open62541 -o server_ctt

