all:
	gcc server.c -I /opt/Linaro/open62541.git/build/ -L /opt/Linaro/open62541.git/build/bin -l open62541 -o server
	gcc client.c -I /opt/Linaro/open62541.git/build/ -L /opt/Linaro/open62541.git/build/bin -l open62541 -o client

